name: diana
channels:
  - pytorch
  - nvidia
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0
  - pytorch-cuda=11.8
  - lightgbm
  - scikit-learn>=1.3
  - numpy>=1.24
  - scipy>=1.10
  - polars>=0.19
  - pandas>=2.0
  - matplotlib>=3.7
  - seaborn>=0.12
  - plotly
  - python-kaleido=0.2.1
  - h5py
  - pyarrow
  - jupyterlab
  - pytest
  - black
  - isort
  - pip
  - pip:
      - pyyaml>=6.0
      - tensorboard
      - tqdm
      - wandb
      - scikit-multilearn